#### Numpy has 11 Datatypes and the characters used to represent them are:*
* integer - i
* boolean - b
* unsigned integer - u
* float - f
* complex float - c
* timedelta - m
* datatime - M
* object - O
* string - S
* unicode string - U
* fixed chunk of memory for other type (void) - V

In [23]:
import numpy as np

In [24]:
#int
a=np.array([1,2,3,4,5,6,7,8],dtype=int)
print(a)
print(a.dtype)

[1 2 3 4 5 6 7 8]
int32


In [25]:
#Float
a=np.array([1,2,3,4,5,6,7,8],dtype=float)
print(a)
print(a.dtype)

[1. 2. 3. 4. 5. 6. 7. 8.]
float64


In [26]:
#String
a=np.array([1,2,3,4,5,6,7,8],dtype=str)
print(a)
print(a.dtype)

['1' '2' '3' '4' '5' '6' '7' '8']
<U1


In [27]:
#complex
a=np.array([1,2,3,4,5,6,7,8],dtype=complex)
print(a)
print(a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j]
complex128


In [28]:
#Boolean
a=np.array([1,2,3,4,5,6,7,8],dtype='bool_')
print(a)
print(a.dtype)

[ True  True  True  True  True  True  True  True]
bool


In [29]:
#Unsigned Integer
a=np.array([1,2,3,4,5,6,7,8],dtype='uint')
print(a)
print(a.dtype)

[1 2 3 4 5 6 7 8]
uint32


In [30]:
#For object
a=np.array([1,2,3,4,5,6,7,8],dtype='O')
print(a)
print(a.dtype)

[1 2 3 4 5 6 7 8]
object


In [31]:
#timedelta
x=np.timedelta64(10, 'M')
print(x)

10 months


In [32]:
#datetime
x=np.array(['2023-05-15', '2002-05-15', '2001-08-08'], dtype='datetime64')
x

array(['2023-05-15', '2002-05-15', '2001-08-08'], dtype='datetime64[D]')

In [33]:
#unicode string
x = np.array([u'\u03bcm', u'\u2202r', u'\u2206\u03bb'], dtype='U')
x

array(['μm', '∂r', '∆λ'], dtype='<U2')

In [34]:
#void
x=np.void([], dtype='V')
x

array([], dtype='|V8')

In [35]:
#complex float ex-2
a=np.array([1+8j,2+5j,6+1j])
print(a)
a.dtype

[1.+8.j 2.+5.j 6.+1.j]


dtype('complex128')